export const exportExcelHeader1: any = [
  'Asset Code',
  'Asset Name',
  'Type Code',
  'Type Name',
  'Unit',
  'Purchase Date',
  'Description',
  'Sponsor',
  'Sponsor Name',
  'Cost',
  'Serial Number',
  'Invoice No.',
  'Invoice Date',
  'Invoice Remark',
  'Department Code',
  'Department Name',
  'Place Code',
  'Place Name',
  'Vendor Code',
  'Vendor Name',
  'Other Vendor Name',
  'Vendor Type',
  'Vendor Email',
  'Vendor Phone',
  'Vendor Fax',
  'Vendor Address',
  'Vendor Contact Person',
  'Vendor Remark',
  'Country Tax Code',
  'Tax Code',
  'Tax Rate',
  'Include Tax',
  'Total',
  'Account Code',
  'Account Name',
  'Brand Code',
  'Brand Name',
  'Cheque No.',
  'Maintenance Period Start',
  'Maintenance Period End',
  'Voucher No.',
  'Voucher Used Date',
  'Remark'
]

export const exportExcelHeader2: any = [
  'assetCode',
  'assetName',
  'typeCode',
  'typeName',
  'unit',
  'buyDate',
  'description',
  'sponsor',
  'sponsorName',
  'cost',
  'serialNum',
  'invoiceNo',
  'invoiceDate',
  'invoiceRemark',
  'deptCode',
  'deptName',
  'placeCode',
  'placeName',
  'vendorCode',
  'vendorName',
  'vendorOtherName',
  'vendorType',
  'vendorEmail',
  'vendorPhone',
  'vendorFax',
  'vendorAddress',
  'vendorContactPerson',
  'vendorRemark',
  'taxCountryCode',
  'taxCode',
  'taxRate',
  'includeTax',
  'afterBeforeTax',
  'accountCode',
  'accountName',
  'brandCode',
  'brandName',
  'chequeNo',
  'maintenancePeriodStart',
  'maintenancePeriodEnd',
  'voucherNo',
  'voucherUsedDate',
  'remark'
]